/* ── Episode sentence data (E1/E2/E3) ── */
// ── EPISODE DATA ──
const EPS=[
// ── E1 泥巴坑 ──
{title:"Charcos de Barro",titleZh:"泥巴坑",dur:187,sentences:[
  {es:"Yo soy Peppa Pig.",chunks:[{word:"Yo",type:"noun",hint:"主詞 I"},{word:"soy",type:"verb",hint:"be動詞"},{word:"Peppa",type:"noun",hint:"名字"},{word:"Pig.",type:"noun",hint:"豬"}],zh:"我是佩佩豬。",en:"I am Peppa Pig.",noteZh:"「soy」= 我是（ser 動詞第一人稱）",noteEn:"soy = I am (1st person of 'ser')"},
  {es:"Este es mi hermano pequeño George.",chunks:[{word:"Este",type:"adj",hint:"這（陽性）"},{word:"es",type:"verb",hint:"be動詞"},{word:"mi",type:"adj",hint:"我的"},{word:"hermano",type:"noun",hint:"兄弟"},{word:"pequeño",type:"adj",hint:"小的"},{word:"George.",type:"noun",hint:"名字"}],zh:"這是我的小弟弟喬治。",en:"This is my little brother George.",noteZh:"「hermano pequeño」= 小弟弟；pequeño 陽性形容詞",noteEn:"'hermano' = brother; 'pequeño' = little (masculine)",
  expand:{
    pattern:"____ es mi [關係] [大小] [名字]",
    note:"Este/Esta 跟著關係詞的性別走 — 選了 hermana 就要用 Esta",
    fixed:["es","mi"],
    groups:[
      {label:"關係詞",key:"rel",options:[
        {es:"hermano",zh:"兄弟",gender:"m"},
        {es:"hermana",zh:"姊妹",gender:"f"},
      ]},
      {label:"大小",key:"size",options:[
        {es:"mayor",zh:"大的（哥/姐）",gender:"both"},
        {es:"pequeño",zh:"小的（弟）",gender:"m"},
        {es:"pequeña",zh:"小的（妹）",gender:"f"},
      ]},
      {label:"名字",key:"name",options:[
        {es:"George",zh:"喬治",gender:"m"},
        {es:"Luna",zh:"露娜",gender:"f"},
        {es:"Vera",zh:"你自己",gender:"f"},
      ]},
    ]
  }},
  {es:"Hoy está lloviendo así que no pueden jugar fuera.",chunks:[{word:"Hoy",type:"noun",hint:"今天"},{word:"está",type:"verb",hint:"be動詞（狀態）"},{word:"lloviendo",type:"verb",hint:"下雨中"},{word:"así que",type:"noun",hint:"所以"},{word:"no",type:"noun",hint:"不"},{word:"pueden",type:"verb",hint:"能夠"},{word:"jugar",type:"verb",hint:"玩"},{word:"fuera.",type:"noun",hint:"外面"}],zh:"今天在下雨，所以不能去外面玩。",en:"Today it is raining so they cannot play outside.",noteZh:"「está lloviendo」= 現在進行式，正在下雨",noteEn:"'está lloviendo' = present continuous, it is raining"},
  {es:"¿Podemos salir a jugar?",chunks:[{word:"¿Podemos",type:"verb",hint:"我們能…嗎"},{word:"salir",type:"verb",hint:"出去"},{word:"a",type:"noun",hint:"去（介詞）"},{word:"jugar?",type:"verb",hint:"玩"}],zh:"我們可以出去玩嗎？",en:"Can we go out to play?",noteZh:"「¿Podemos…?」= 我們可以…嗎？（poder 動詞一人稱複數）",noteEn:"'¿Podemos?' = Can we? (poder = to be able to)"},
  {es:"Peppa, debes ponerte las botas de agua.",chunks:[{word:"Peppa,",type:"noun",hint:"名字"},{word:"debes",type:"verb",hint:"你必須"},{word:"ponerte",type:"verb",hint:"穿上"},{word:"las",type:"adj",hint:"定冠詞複數"},{word:"botas",type:"noun",hint:"靴子"},{word:"de agua.",type:"noun",hint:"雨靴"}],zh:"佩佩，你必須穿上雨靴。",en:"Peppa, you must put on your wellies.",noteZh:"「debes + 原形動詞」= 你必須做…",noteEn:"'debes + infinitive' = you must do..."},
  {es:"¡Me encanta saltar en los charcos!",chunks:[{word:"¡Me",type:"noun",hint:"我（受詞）"},{word:"encanta",type:"verb",hint:"超愛"},{word:"saltar",type:"verb",hint:"跳"},{word:"en",type:"noun",hint:"在…裡"},{word:"los",type:"adj",hint:"定冠詞複數"},{word:"charcos!",type:"noun",hint:"水坑"}],zh:"我超愛在水坑裡跳！",en:"I love jumping in puddles!",noteZh:"「Me encanta」= 我超愛，比 me gusta 更強烈",noteEn:"'Me encanta' = I love it (stronger than 'me gusta')"},
  {es:"Peppa ha encontrado un charco pequeño.",chunks:[{word:"Peppa",type:"noun",hint:"名字"},{word:"ha",type:"verb",hint:"助動詞"},{word:"encontrado",type:"verb",hint:"找到了"},{word:"un",type:"adj",hint:"一個（陽性）"},{word:"charco",type:"noun",hint:"水坑"},{word:"pequeño.",type:"adj",hint:"小的"}],zh:"佩佩找到了一個小水坑。",en:"Peppa has found a small puddle.",noteZh:"「ha encontrado」= 現在完成式，已經找到了",noteEn:"'ha encontrado' = has found (present perfect tense)"},
  {es:"¡Ese charco sí que es grande!",chunks:[{word:"¡Ese",type:"adj",hint:"那個"},{word:"charco",type:"noun",hint:"水坑"},{word:"sí que",type:"noun",hint:"真的是"},{word:"es",type:"verb",hint:"be動詞"},{word:"grande!",type:"adj",hint:"大的"}],zh:"那個水坑真的好大！",en:"That puddle really is big!",noteZh:"「sí que」= 強調語氣，真的是、確實是",noteEn:"'sí que' adds emphasis: it really is / it truly is"},
  {es:"No pasa nada. Sólo es barro.",chunks:[{word:"No",type:"noun",hint:"不"},{word:"pasa",type:"verb",hint:"發生"},{word:"nada.",type:"noun",hint:"什麼"},{word:"Sólo",type:"adj",hint:"只是"},{word:"es",type:"verb",hint:"be動詞"},{word:"barro.",type:"noun",hint:"泥巴"}],zh:"沒關係，只是泥巴而已。",en:"It's okay. It's only mud.",noteZh:"「No pasa nada」= 沒關係，西語最常用的安慰語！",noteEn:"'No pasa nada' = It's okay / No worries. Super common!"},
  {es:"A todos les encanta saltar en los charcos de barro.",chunks:[{word:"A todos",type:"noun",hint:"所有人"},{word:"les",type:"noun",hint:"他們（受詞）"},{word:"encanta",type:"verb",hint:"超愛"},{word:"saltar",type:"verb",hint:"跳"},{word:"en",type:"noun",hint:"在…裡"},{word:"los charcos",type:"noun",hint:"水坑"},{word:"de barro.",type:"noun",hint:"泥巴"}],zh:"所有人都超愛在泥巴坑裡跳！",en:"Everyone loves jumping in muddy puddles!",noteZh:"「A todos les encanta」= 所有人都超愛，第三人稱複數",noteEn:"'A todos les encanta' = everyone loves it (3rd person plural)"}
]},

// ── E2 恐龍先生不見了 ──
{title:"El Señor Dinosaurio Se Ha Perdido",titleZh:"恐龍先生不見了",dur:195,sentences:[
  {es:"El juguete favorito de George es el señor Dinosaurio.",chunks:[{word:"El",type:"adj",hint:"定冠詞"},{word:"juguete",type:"noun",hint:"玩具"},{word:"favorito",type:"adj",hint:"最喜歡的"},{word:"de George",type:"noun",hint:"喬治的"},{word:"es",type:"verb",hint:"be動詞"},{word:"el señor",type:"noun",hint:"先生"},{word:"Dinosaurio.",type:"noun",hint:"恐龍"}],zh:"喬治最喜歡的玩具是恐龍先生。",en:"George's favourite toy is Mr Dinosaur.",noteZh:"「favorito」= 最喜歡的，名詞後置形容詞",noteEn:"'favorito' = favourite (adjective placed after noun)"},
  {es:"Cuando George se va a la cama el señor Dinosaurio se acurruca a su lado.",chunks:[{word:"Cuando",type:"noun",hint:"當…時候"},{word:"George",type:"noun",hint:"名字"},{word:"se va",type:"verb",hint:"去"},{word:"a la cama",type:"noun",hint:"去睡覺"},{word:"el señor Dinosaurio",type:"noun",hint:"恐龍先生"},{word:"se acurruca",type:"verb",hint:"蜷縮"},{word:"a su lado.",type:"noun",hint:"在他身旁"}],zh:"當喬治上床睡覺時，恐龍先生就蜷縮在他身旁。",en:"When George goes to bed, Mr Dinosaur cuddles up beside him.",noteZh:"「se va a la cama」= 上床睡覺；「a su lado」= 在他旁邊",noteEn:"'se va a la cama' = goes to bed; 'a su lado' = beside him"},
  {es:"George ha perdido al señor Dinosaurio.",chunks:[{word:"George",type:"noun",hint:"名字"},{word:"ha",type:"verb",hint:"助動詞"},{word:"perdido",type:"verb",hint:"弄丟了"},{word:"al",type:"adj",hint:"a + el"},{word:"señor",type:"noun",hint:"先生"},{word:"Dinosaurio.",type:"noun",hint:"恐龍"}],zh:"喬治把恐龍先生弄丟了。",en:"George has lost Mr Dinosaur.",noteZh:"「ha perdido」= 現在完成式，已經弄丟了",noteEn:"'ha perdido' = has lost (present perfect tense)"},
  {es:"No te preocupes George, entre todos lo encontraremos.",chunks:[{word:"No te",type:"noun",hint:"不要"},{word:"preocupes",type:"verb",hint:"擔心"},{word:"George,",type:"noun",hint:"名字"},{word:"entre todos",type:"noun",hint:"大家一起"},{word:"lo",type:"noun",hint:"它（受詞）"},{word:"encontraremos.",type:"verb",hint:"會找到"}],zh:"不要擔心喬治，我們大家一起會找到牠的。",en:"Don't worry George, together we will find it.",noteZh:"「No te preocupes」= 不要擔心，反身動詞命令句",noteEn:"'No te preocupes' = Don't worry (reflexive imperative)"},
  {es:"Un detective es una persona muy buena encontrando cosas.",chunks:[{word:"Un",type:"adj",hint:"一個（陽性）"},{word:"detective",type:"noun",hint:"偵探"},{word:"es",type:"verb",hint:"be動詞"},{word:"una persona",type:"noun",hint:"一個人"},{word:"muy",type:"adj",hint:"非常"},{word:"buena",type:"adj",hint:"擅長的（陰性）"},{word:"encontrando",type:"verb",hint:"找東西"},{word:"cosas.",type:"noun",hint:"東西"}],zh:"偵探是一個非常擅長找東西的人。",en:"A detective is a person who is very good at finding things.",noteZh:"「muy buena encontrando」= 非常擅長於做某事",noteEn:"'muy buena encontrando' = very good at finding (gerund phrase)"},
  {es:"George siempre se trae al señor Dinosaurio a la bañera.",chunks:[{word:"George",type:"noun",hint:"名字"},{word:"siempre",type:"adj",hint:"總是"},{word:"se trae",type:"verb",hint:"帶著"},{word:"al señor",type:"noun",hint:"先生"},{word:"Dinosaurio",type:"noun",hint:"恐龍"},{word:"a la bañera.",type:"noun",hint:"到浴缸"}],zh:"喬治總是帶著恐龍先生去洗澡。",en:"George always brings Mr Dinosaur to the bath.",noteZh:"「siempre」= 總是，頻率副詞放在動詞前",noteEn:"'siempre' = always (frequency adverb, placed before verb)"},
  {es:"¡Ya lo sé dónde está el señor Dinosaurio!",chunks:[{word:"¡Ya",type:"adj",hint:"已經/就是"},{word:"lo sé",type:"verb",hint:"我知道了"},{word:"dónde está",type:"verb",hint:"在哪裡"},{word:"el señor",type:"noun",hint:"先生"},{word:"Dinosaurio!",type:"noun",hint:"恐龍"}],zh:"我知道恐龍先生在哪裡了！",en:"I know where Mr Dinosaur is!",noteZh:"「Ya lo sé」= 我知道了，ya 表示已然發生",noteEn:"'Ya lo sé' = I already know! 'ya' indicates something just realized"},
  {es:"El señor Dinosaurio no está en la cama de George.",chunks:[{word:"El señor",type:"noun",hint:"先生"},{word:"Dinosaurio",type:"noun",hint:"恐龍"},{word:"no está",type:"verb",hint:"不在"},{word:"en",type:"noun",hint:"在"},{word:"la cama",type:"noun",hint:"床"},{word:"de George.",type:"noun",hint:"喬治的"}],zh:"恐龍先生不在喬治的床上。",en:"Mr Dinosaur is not in George's bed.",noteZh:"「no está」= 不在（用 estar 表示位置）",noteEn:"'no está' = is not there (uses 'estar' for location)"},
  {es:"Peppa y papá Pig están jugando a las damas.",chunks:[{word:"Peppa",type:"noun",hint:"名字"},{word:"y",type:"noun",hint:"和"},{word:"papá Pig",type:"noun",hint:"豬爸爸"},{word:"están",type:"verb",hint:"正在"},{word:"jugando",type:"verb",hint:"玩"},{word:"a las damas.",type:"noun",hint:"下西洋棋"}],zh:"佩佩和豬爸爸正在下西洋棋。",en:"Peppa and Daddy Pig are playing draughts.",noteZh:"「están jugando」= 現在進行式，正在玩",noteEn:"'están jugando' = are playing (present continuous with estar)"},
  {es:"¡Ya lo sé, habéis estado saltando en los charcos de barro!",chunks:[{word:"¡Ya lo sé,",type:"verb",hint:"我知道了"},{word:"habéis",type:"verb",hint:"你們（助動詞）"},{word:"estado",type:"verb",hint:"一直在"},{word:"saltando",type:"verb",hint:"跳"},{word:"en los charcos",type:"noun",hint:"在水坑裡"},{word:"de barro!",type:"noun",hint:"泥巴"}],zh:"我知道了，你們一直在泥巴坑裡跳！",en:"I know, you've been jumping in muddy puddles!",noteZh:"「habéis estado + 動名詞」= 現在完成進行式，一直在做…",noteEn:"'habéis estado + gerund' = you have been doing... (present perfect continuous)"}
]},

// ── E3 最好的朋友 ──
{title:"La Mejor Amiga",titleZh:"最好的朋友",dur:192,sentences:[
  {es:"Peppa está esperando a su mejor amiga, Susi Sheep.",chunks:[{word:"Peppa",type:"noun",hint:"名字"},{word:"está",type:"verb",hint:"be動詞（狀態）"},{word:"esperando",type:"verb",hint:"等待"},{word:"a su",type:"noun",hint:"她的"},{word:"mejor",type:"adj",hint:"最好的"},{word:"amiga,",type:"noun",hint:"朋友（女）"},{word:"Susi Sheep.",type:"noun",hint:"名字"}],zh:"佩佩正在等她最好的朋友蘇西羊。",en:"Peppa is waiting for her best friend, Suzy Sheep.",noteZh:"「está esperando」= 現在進行式，正在等",noteEn:"'está esperando' = is waiting (present continuous)"},
  {es:"Peppa quiere mucho a Susi y Susi quiere mucho a Peppa.",chunks:[{word:"Peppa",type:"noun",hint:"名字"},{word:"quiere",type:"verb",hint:"愛/喜歡"},{word:"mucho",type:"adj",hint:"很多"},{word:"a Susi",type:"noun",hint:"蘇西（受詞）"},{word:"y",type:"noun",hint:"和"},{word:"Susi",type:"noun",hint:"名字"},{word:"quiere",type:"verb",hint:"愛/喜歡"},{word:"mucho",type:"adj",hint:"很多"},{word:"a Peppa.",type:"noun",hint:"佩佩（受詞）"}],zh:"佩佩非常喜歡蘇西，蘇西也非常喜歡佩佩。",en:"Peppa loves Suzy very much and Suzy loves Peppa very much.",noteZh:"「querer + mucho」= 非常喜歡、愛，人名前加 a",noteEn:"'querer a alguien' = to love someone. 'a' is required before person"},
  {es:"Son las mejores amigas.",chunks:[{word:"Son",type:"verb",hint:"她們是"},{word:"las",type:"adj",hint:"定冠詞複數"},{word:"mejores",type:"adj",hint:"最好的（複數）"},{word:"amigas.",type:"noun",hint:"朋友（女複數）"}],zh:"她們是最好的朋友。",en:"They are best friends.",noteZh:"「mejores amigas」= 最好的朋友；mejor 的複數形",noteEn:"'mejores' = best (plural of 'mejor'); 'amigas' = female friends"},
  {es:"¡No George! Este juego es solo para niñas mayores.",chunks:[{word:"¡No",type:"noun",hint:"不"},{word:"George!",type:"noun",hint:"名字"},{word:"Este",type:"adj",hint:"這個"},{word:"juego",type:"noun",hint:"遊戲"},{word:"es",type:"verb",hint:"be動詞"},{word:"solo para",type:"adj",hint:"只給"},{word:"niñas",type:"noun",hint:"女孩們"},{word:"mayores.",type:"adj",hint:"大一點的"}],zh:"不行喬治！這個遊戲只給大一點的女孩玩。",en:"No George! This game is just for older girls.",noteZh:"「solo para」= 只給、只限；「niñas mayores」= 大一點的女孩",noteEn:"'solo para' = only for; 'niñas mayores' = older girls"},
  {es:"¡Soy una princesa salida de un cuento!",chunks:[{word:"¡Soy",type:"verb",hint:"我是"},{word:"una",type:"adj",hint:"一個（陰性）"},{word:"princesa",type:"noun",hint:"公主"},{word:"salida",type:"adj",hint:"出來的"},{word:"de un cuento!",type:"noun",hint:"從故事書"}],zh:"我是從故事書裡走出來的公主！",en:"I am a princess from a fairy tale!",noteZh:"「salida de un cuento」= 從故事書裡走出來的",noteEn:"'salida de un cuento' = come out of a story / fairy tale princess"},
  {es:"A George no le gusta jugar solo.",chunks:[{word:"A George",type:"noun",hint:"喬治（受詞標記）"},{word:"no",type:"noun",hint:"不"},{word:"le gusta",type:"verb",hint:"喜歡"},{word:"jugar",type:"verb",hint:"玩"},{word:"solo.",type:"adj",hint:"單獨"}],zh:"喬治不喜歡一個人玩。",en:"George doesn't like to play alone.",noteZh:"「A + 人 + le gusta」= 某人喜歡，西語必學句型！",noteEn:"'A + person + le gusta' = someone likes. Key Spanish structure!"},
  {es:"Yo seré la doctora y tú serás la enfermera.",chunks:[{word:"Yo",type:"noun",hint:"我"},{word:"seré",type:"verb",hint:"我將是"},{word:"la doctora",type:"noun",hint:"女醫生"},{word:"y tú",type:"noun",hint:"和你"},{word:"serás",type:"verb",hint:"你將是"},{word:"la enfermera.",type:"noun",hint:"護士（女）"}],zh:"我來當醫生，你來當護士。",en:"I will be the doctor and you will be the nurse.",noteZh:"「seré / serás」= ser 動詞的未來式，我/你將是",noteEn:"'seré / serás' = I will be / you will be (future tense of 'ser')"},
  {es:"Ahora George, respira hondo. Después tose.",chunks:[{word:"Ahora",type:"noun",hint:"現在"},{word:"George,",type:"noun",hint:"名字"},{word:"respira",type:"verb",hint:"呼吸"},{word:"hondo.",type:"adj",hint:"深深地"},{word:"Después",type:"noun",hint:"然後"},{word:"tose.",type:"verb",hint:"咳嗽"}],zh:"現在喬治，深呼吸。然後咳嗽。",en:"Now George, breathe deeply. Then cough.",noteZh:"「respira hondo」= 深呼吸，命令式動詞直接用",noteEn:"'respira hondo' = breathe deeply (imperative form, informal)"},
  {es:"Creo que tienes el corazón un poco flojo.",chunks:[{word:"Creo que",type:"verb",hint:"我認為"},{word:"tienes",type:"verb",hint:"你有"},{word:"el corazón",type:"noun",hint:"心臟"},{word:"un poco",type:"adj",hint:"有點"},{word:"flojo.",type:"adj",hint:"虛弱的"}],zh:"我認為你的心臟有點虛弱。",en:"I think your heart is a little weak.",noteZh:"「Creo que」= 我認為，後接完整子句",noteEn:"'Creo que' = I think that... (followed by a full clause)"},
  {es:"Todos necesitan muchas galletas para curarse.",chunks:[{word:"Todos",type:"noun",hint:"所有人"},{word:"necesitan",type:"verb",hint:"需要"},{word:"muchas",type:"adj",hint:"很多（陰性複數）"},{word:"galletas",type:"noun",hint:"餅乾"},{word:"para",type:"noun",hint:"為了"},{word:"curarse.",type:"verb",hint:"治好"}],zh:"所有人都需要很多餅乾才能康復。",en:"Everyone needs lots of cookies to get better.",noteZh:"「para + 原形動詞」= 為了做某事；「curarse」= 康復",noteEn:"'para + infinitive' = in order to do; 'curarse' = to recover"}
]}
];

